### ISSUE TITLE
About the PR cureve of Fig. 4 in the paper

### ISSUE THREAD

**Issue by MAX-OTW** [sparolab/sonar_context#1]
Hello, @hogyun2 @sparolab ,-I really appreciate for your work！Congratulations :)
The PR cureve of Fig. 4  in the paper look great. Currently I want to try to implement them but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.
I am always looking forward to your kind response.
Best regards.

**Comment by hogyun2** [comment]
Thank you for your interest. :)
We don't provide code for PR curves. However, when ground truth exists for the dataset, if you know the number of revisited places, you can draw the precision and recall.
If you change the threshold of each cosine distance and find the precision and recall, you can depict the pr curve.

**Comment by hogyun2** [comment]
Hello, @MAX-OTW, thank you for your interest :).
Maybe, this link(https://github.com/ameya98/pr2roc/blob/master/demo.ipynb) will be helpful for your reference.

Sincerely,
Hogyun Kim
