### ISSUE TITLE
the code for slam location

### ISSUE THREAD

**Issue by anghaocheng** [sparolab/sonar_context#2]
Hello, thank you very much for sharing this excellent work; but in the public code, I did not see the code for processing the slam positioning part. I see that you performed the underwater positioning of the ARACATI data set in the paper. This part of the code Where is the reference?

**Comment by hogyun2** [comment]
Thank you for your interest in my work. I'm sorry that our slam code is not public. But you can use the reference as this link (https://github.com/gisbi-kim/PyICP-SLAM). His work shows the minisam that leverages the slam positioning part.

**Comment by anghaocheng** [comment]
OK, thank you very much
