### ISSUE TITLE
Could I get the configuration file to test the code on the ARACATI dataset?

### ISSUE THREAD

**Issue by donghwijung** [sparolab/sonar_context#3]
Hello, thank you for sharing this awesome code 👍

Could I get the configuration file to test the code on the ARACATI dataset?

I tested the code on ARACATI dataset by using the configuration as below:

`
--try_gap_loop_detection 1
`
`
--try_gap_pose 1
`
`
--col_threshold 0.045
`
`
--row_threshold 0.072 
`
`
--img_dir Datasets/ARACATI/image/
`
`
--pose_base_dir Datasets/ARACATI/pose/pose.csv
`
`
--exclude_recent_nodes 30
`
`
--sc Datasets/ARACATI/SC/{}.npy
`
`
--pk Datasets/ARACATI/PK/{}.npy
`
`
--csvx 3
`
`
--csvy 7
`

However, I got a result which is different from yours described in the paper
![result_aracati_3d](https://github.com/sparolab/sonar_context/assets/73815549/01d9e9cb-95ee-4881-9926-85d3c4975b88)
![result_aracati_2d](https://github.com/sparolab/sonar_context/assets/73815549/b0a3dfbe-7956-4e5f-b8c0-caf7e4b587ab)

Could you let me know which configuration settings should be modified?

Thank you
Donghwi

**Comment by hogyun2** [comment]
Dear Donghwi Jung,

I would like to express my gratitude for your interest in my paper and
code. The configuration provided above is tailored for the HOLOOCEAN
datasets, and as a result, the outcomes are expected to align accordingly.

When applying the methods to the Aracati dataset, it is crucial to note
that the image processing, sampling, and exclusion of nodes, as detailed in
our paper, may lead to varying results. Therefore, I recommend directly
printing the similarity measurements and adjusting the results accordingly
before plotting.

Thank you once again for your attention and consideration.

Best regards, Hogyun Kim


2023년 11월 17일 (금) 오전 1:14, Donghwi Jung ***@***.***>님이 작성:

**Comment by donghwijung** [comment]
Thank you for answering

I will check the details in the paper :)

**Comment by donghwijung** [comment]
Thank you for answering

I will check the details in the paper :)

**Comment by yingzi-666** [comment]
Have you solved this problem? Could you share your configuration file?I don't know how to set it up.

**Comment by hogyun2** [comment]
--try_gap_loop_detection 1              # parameter for frame. If this parameter is 10, skip 10 and use 100 out of 1000
--try_gap_pose 1                                # parameter for frame. If this parameter is 10, skip 10 and use 100 out of 1000
--col_threshold 0.045                        # threshold for column shifting similarity comparison
--row_threshold 0.072                      # threshold for row shifting similarity comparison
--exclude_recent_nodes 30              # parameters for the number of nearby nodes to be removed based on the current node 
                                                                 for similarity comparisons
--csvx 3                                                 # Column number of x positions in CSV
--csvy 7                                                 # Column number of y positions in CSV

@yingzi-666 Thank you for your interest in our paper, I add a description of the parameters.
