### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by QKC315** [sparolab/sonar_context#4]
Hello, thank you for sharing the data, I am not familiar with ros, may I ask how you use the aracati2017 data set into your program？Thank you very much!

**Comment by hogyun2** [comment]
You need to install ros in Ubuntu first. Please refer to the [following link](http://wiki.ros.org/noetic/Installation/Ubuntu) for the installation process of ros.
Then, after downloading the rosbag from the [following link](https://drive.google.com/file/d/1dbpfd3jElTdHmnceKE5RL8hzU-BDYaW-/view), put it in the bags folder of [this link](https://github.com/matheusbg8/aracati2017.git), and follow the github readme of that link.
