### ISSUE TITLE
pose.csv

### ISSUE THREAD

**Issue by QKC315** [sparolab/sonar_context#5]
Hi , thanks for this repository!! Can you give us an example of pose.csv file for the project ?
I dont understand how the csv is composed. Thanks.
Best regards.

**Comment by hogyun2** [comment]
Thank you for your interest in our project. 
First of all, I'm sorry for the confusion. 
You can use Google Drive's pose.csv file, and pose.csv is lined up with a 4x4 matrix. 
That is, it consists of r11 r12 r13 t1 r21 r22 r23 t2 r31 r32 r33 t3 0 0 0 1.

**Comment by tahaaideveloper** [comment]
Hi, Thank you for this good repository.
How can I create my own ‌pose.csv in holoocean?

**Comment by hogyun2** [comment]
@tahaaideveloper Thank you for your interest in our method.
In our case, we use an lcm message (http://lcm-proj.github.io/lcm/) to obtain the ground truth pose.
